{{- if .Values.config.gun.pwd }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myriad-claimer.gunPwdSecretName" . }}
type: Opaque
data:
  gunPwd: {{ .Values.config.gun.pwd | b64enc }}
{{- end }}
